name: CloudPub Client
slug: cloudpub
version: 1.1.0
description: >-
  Внешний доступ к Home Assistant и другим локальным ресурсам без «белого» IP (за NAT)
url: https://github.com/black-roland/hassio-addon-cloudpub
init: false
startup: application
boot: auto
arch:
  - aarch64
  - amd64
  - armv7
map:
  - type: addon_config
    read_only: False
stage: experimental
options:
  token: ""
  services:
    - type: "http"
      local_addr: "homeassistant:8123"
      name: "homeassistant"
schema:
  token: str
  services:
    - type: list(http|https|tcp|udp|rtsp|1c)
      local_addr: str
      name: str?
