build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:9.1.0
  amd64: ghcr.io/hassio-addons/debian-base:9.1.0
  armhf: ghcr.io/hassio-addons/debian-base:8.1.4
  armv7: ghcr.io/hassio-addons/debian-base:8.1.4
  i386: ghcr.io/hassio-addons/debian-base:8.1.4
codenotary:
  base_image: codenotary@frenck.dev
